[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
port = 5000
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[global]
dataFrameSerialization = "legacy"

[runner]
fastReruns = true

[logger]
level = "error"
